version: 2

defaults: &defaults
  working_directory: ~/grc
  docker:
    - image: circleci/node:8.9.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }} # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/grc
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grc
      - run:
          name: Run tests
          command: npm run test:prod

  deploy-npm:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grc
      - run:
          name: Semantic release
          command: npm run semantic-release

  deploy-docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/grc
      - run:
          name: Deploy docs
          command: npm run deploy:docs

workflows:
  version: 2
  test-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - test:
          filters:
            branches:
              ignore: gh-pages
          requires:
            - build
      - deploy-docs:
          filters:
            branches:
              only: master
              ignore: gh-pages
          requires:
            - build
            - test
      - deploy-npm:
          filters:
              branches:
                only: master
                ignore: gh-pages
              requires:
                - build
                - test
